#!/bin/sh
set -eu
umask 077

fail() { printf '%s / %s\n' "$1" "$2" >&2; exit 1; }
command -v docker >/dev/null 2>&1 || fail 'Docker is required.' '请先安装 Docker。'
docker compose version >/dev/null 2>&1 || fail 'Docker Compose v2 is required.' '请先安装 Docker Compose v2。'
docker info >/dev/null 2>&1 || fail 'Cannot connect to Docker.' '无法连接 Docker，请确认服务及当前用户权限。'

INSTALL_DIR="${INSTALL_DIR:-$PWD/pudding-relay}"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
setting() {
  if [ -f .env ]; then
    awk -v key="$1" 'index($0, key "=")==1 {value=substr($0,length(key)+2)} END {print value}' .env
  fi
}
# .env is data, not shell code. Environment arguments override persisted settings.
IMAGE="${IMAGE-$(setting IMAGE)}"
IMAGE="${IMAGE:-teatak/pudding-relay:latest}"
PORT="${PORT-$(setting PORT)}"
PORT="${PORT:-9623}"
BIND_ADDRESS="${BIND_ADDRESS-$(setting BIND_ADDRESS)}"
BIND_ADDRESS="${BIND_ADDRESS:-127.0.0.1}"
TRUSTED_PROXIES="${TRUSTED_PROXIES-$(setting TRUSTED_PROXIES)}"
NETWORK="${NETWORK-$(setting NETWORK)}"

case "$TRUSTED_PROXIES" in *[!0-9a-fA-F.:/,]*) fail 'TRUSTED_PROXIES must contain comma-separated CIDRs.' 'TRUSTED_PROXIES 请填写逗号分隔的 CIDR。' ;; esac
case "$IMAGE" in -*|*[!a-zA-Z0-9._/@:-]*) fail 'Invalid IMAGE reference.' 'IMAGE 镜像地址无效。' ;; esac
case "$PORT" in ''|*[!0-9]*) fail 'PORT must be between 1 and 65535.' 'PORT 必须为 1 到 65535。' ;; esac
[ "$PORT" -ge 1 ] && [ "$PORT" -le 65535 ] || fail 'PORT must be between 1 and 65535.' 'PORT 必须为 1 到 65535。'
case "$BIND_ADDRESS" in ''|*[!0-9a-fA-F.:]*) fail 'BIND_ADDRESS must be a host IP address.' 'BIND_ADDRESS 必须为宿主机 IP 地址。' ;; esac
case "$NETWORK" in *[!a-zA-Z0-9_.-]*) fail 'Invalid NETWORK name.' 'NETWORK 网络名无效。' ;; esac
if [ -n "$NETWORK" ]; then
  docker network inspect "$NETWORK" >/dev/null 2>&1 || fail 'NETWORK does not exist.' '指定的 Docker 网络不存在。'
fi

# A failed image download must not replace a working installation's settings.
docker pull "$IMAGE"
docker run --rm --entrypoint /bin/sh "$IMAGE" -c 'test -r /assets/index.html' || fail 'This image is missing the browser UI.' '此镜像缺少浏览器界面资源。'

mkdir -p secrets
chmod 700 secrets
relay_secret_tmp=''
relay_env_tmp=''
relay_compose_tmp=''
relay_make_tmp=''
cleanup() {
  for relay_file in "$relay_secret_tmp" "$relay_env_tmp" "$relay_compose_tmp" "$relay_make_tmp"; do
    [ -z "$relay_file" ] || rm -f "$relay_file"
  done
}
trap cleanup EXIT
trap 'exit 1' HUP INT TERM
if [ ! -f secrets/admin-secret ]; then
  relay_secret_tmp=$(mktemp secrets/.admin-secret.XXXXXX)
  od -An -N32 -tx1 /dev/urandom | tr -d ' \n' > "$relay_secret_tmp"
  [ "$(wc -c < "$relay_secret_tmp" | tr -d ' ')" -eq 64 ] || fail 'Cannot generate the admin secret.' '无法生成管理员密钥。'
  printf '\n' >> "$relay_secret_tmp"
  mv "$relay_secret_tmp" secrets/admin-secret
  relay_secret_tmp=''
fi
[ "$(wc -c < secrets/admin-secret | tr -d ' ')" -ge 32 ] || fail 'The saved admin secret is invalid.' '已保存的管理员密钥无效。'
# Docker bind-mounted secrets retain host permissions; the parent directory is private.
chmod 444 secrets/admin-secret

relay_env_tmp=$(mktemp .env.XXXXXX)
if [ -f .env ]; then
  awk '!/^(IMAGE|PORT|BIND_ADDRESS|PUBLIC_URL|TRUSTED_PROXIES|NETWORK)=/' .env > "$relay_env_tmp"
fi
cat >> "$relay_env_tmp" <<EOF
IMAGE=$IMAGE
PORT=$PORT
BIND_ADDRESS=$BIND_ADDRESS
TRUSTED_PROXIES=$TRUSTED_PROXIES
NETWORK=$NETWORK
EOF

relay_compose_tmp=$(mktemp .compose.XXXXXX)
cat > "$relay_compose_tmp" <<'EOF'
# Generated by pudding-relay/install.sh. Configure .env and rerun the installer.
services:
  relay:
    image: ${IMAGE}
    ports:
      - target: 9623
        published: "${PORT}"
        host_ip: "${BIND_ADDRESS}"
    environment:
      PUDDING_RELAY_TRUSTED_PROXIES: "${TRUSTED_PROXIES}"
      PUDDING_RELAY_ADMIN_SECRET_FILE: /run/secrets/admin_secret
      PUDDING_RELAY_ASSETS_DIR: /assets
    secrets:
      - admin_secret
    volumes:
      - relay_data:/data
    restart: unless-stopped
    read_only: true
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    stop_grace_period: 10s
secrets:
  admin_secret:
    file: ./secrets/admin-secret
volumes:
  relay_data:
EOF
if [ -n "$NETWORK" ]; then
  cat >> "$relay_compose_tmp" <<'EOF'
networks:
  default:
    external: true
    name: ${NETWORK}
EOF
fi

relay_make_tmp=$(mktemp .makefile.XXXXXX)
cat > "$relay_make_tmp" <<'EOF'
.PHONY: start upgrade restart stop logs status
start:
	docker compose -f compose.yaml up -d --wait --wait-timeout 120
upgrade:
	docker compose -f compose.yaml pull
	docker compose -f compose.yaml up -d --wait --wait-timeout 120
restart:
	docker compose -f compose.yaml restart relay
stop:
	docker compose -f compose.yaml down
logs:
	docker compose -f compose.yaml logs -f relay
status:
	docker compose -f compose.yaml ps
EOF

docker compose --env-file "$relay_env_tmp" -f "$relay_compose_tmp" config --quiet
mv "$relay_env_tmp" .env
relay_env_tmp=''
mv "$relay_compose_tmp" compose.yaml
relay_compose_tmp=''
mv "$relay_make_tmp" makefile
relay_make_tmp=''
docker compose -f compose.yaml up -d --wait --wait-timeout 120
printf '\nPudding Relay is running / Pudding Relay 已启动\n'
printf 'Install directory / 安装目录: %s\n' "$INSTALL_DIR"
printf 'Local admin / 本机管理地址: http://127.0.0.1:%s/admin\n' "$PORT"
printf 'HTTP bind / HTTP 绑定地址: %s:%s\n' "$BIND_ADDRESS" "$PORT"
printf 'Admin secret file / 管理员密钥文件: %s/secrets/admin-secret\n' "$(pwd)"
printf 'Commands / 管理命令: make upgrade | restart | stop | logs | status\n'
