package httpserver

import (
	"io"
	"net/http"
)

func (r *Relay) adminPage(w http.ResponseWriter, req *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("Content-Security-Policy", "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	_, _ = io.WriteString(w, adminHTML)
}

const adminHTML = `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pudding Relay</title>
<style>body{font:16px system-ui;margin:3rem auto;padding:0 1rem;max-width:760px;color:#252423;background:#faf9f7}input,button,select{font:inherit;padding:.6rem;margin:.3rem;border:1px solid #bbb;border-radius:6px}button{cursor:pointer}label{display:block}table{width:100%;border-collapse:collapse}td,th{padding:.7rem;text-align:left;border-bottom:1px solid #ddd}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eee;padding:1rem}small{display:block;color:#555}.row{display:flex;flex-wrap:wrap;align-items:center}</style>
<header class="row"><h1>Pudding Relay</h1><select id="lang" aria-label="Language"><option value="en">English</option><option value="zh">简体中文</option></select></header>
<p id="intro"></p><form id="login"><label id="secretLabel" for="secret"></label><input id="secret" type="password" autocomplete="off" required minlength="32"><button id="connect"></button></form>
<section id="manage" hidden><h2 id="newLabel"></h2><form id="register"><label id="idLabel" for="desktopID"></label><input id="desktopID" required maxlength="128" pattern="[A-Za-z0-9_-]+"><small id="idHelp"></small><label id="labelLabel" for="label"></label><input id="label" maxlength="256"><button id="create"></button></form><pre id="credential" hidden></pre><button id="refresh"></button><table><thead><tr><th id="desktopHead"></th><th id="stateHead"></th><th id="actionHead"></th></tr></thead><tbody id="desktops"></tbody></table></section><p id="message" role="status"></p>
<script>
const $=id=>document.getElementById(id);let secret='',locale='en';const words={en:{intro:'Register a desktop using its existing Pudding desktop ID. Credentials are shown once. The relay stores only credential digests.',secretLabel:'Admin secret',connect:'Connect',newLabel:'Register desktop',idLabel:'Desktop ID',idHelp:'Copy the desktop ID from Pudding Settings → Remote access.',labelLabel:'Label',create:'Create credential',refresh:'Refresh',desktopHead:'Desktop',stateHead:'Status',actionHead:'Action',online:'Online',offline:'Offline',revoke:'Revoke',confirm:'Revoke this desktop credential and disconnect its tunnel?',once:'Save this credential now. It will not be displayed again.',error:'Request failed',setup:'Enter this relay URL, desktop ID and credential in Pudding Settings → Remote access.',revoked:'Credential revoked'},zh:{intro:'使用 Pudding 已有的桌面 ID 登记电脑。凭据仅显示一次，中继仅保存凭据摘要。',secretLabel:'管理员密钥',connect:'连接',newLabel:'登记电脑',idLabel:'桌面 ID',idHelp:'从 Pudding 设置 → 远程访问复制桌面 ID。',labelLabel:'名称',create:'创建凭据',refresh:'刷新',desktopHead:'电脑',stateHead:'状态',actionHead:'操作',online:'在线',offline:'离线',revoke:'撤销',confirm:'撤销此电脑凭据并断开隧道？',once:'请立即保存凭据，之后不会再次显示。',error:'请求失败',setup:'在 Pudding 设置 → 远程访问填写本中继地址、桌面 ID 和凭据。',revoked:'凭据已撤销'}};function tr(k){return words[locale][k]}function localize(){document.documentElement.lang=locale==='zh'?'zh-CN':'en';for(const id of ['intro','secretLabel','connect','newLabel','idLabel','idHelp','labelLabel','create','refresh','desktopHead','stateHead','actionHead'])$(id).textContent=tr(id)}$('lang').onchange=()=>{locale=$('lang').value;localize();if(secret)load().catch(showError)};localize();
function showError(e){$('message').textContent=e.message}
async function api(path,options={}){const response=await fetch('/admin/api/desktops'+path,{...options,headers:{Authorization:'Bearer '+secret,'Content-Type':'application/json'},cache:'no-store'});if(!response.ok)throw new Error(tr('error')+' ('+response.status+')');return response.status===204?null:response.json()}
async function load(){const result=await api('');$('desktops').replaceChildren();for(const item of result.desktops){const row=document.createElement('tr'),name=document.createElement('td'),state=document.createElement('td'),action=document.createElement('td'),button=document.createElement('button'),link=document.createElement('a');link.href='/d/'+encodeURIComponent(item.desktopID)+'/';link.textContent=item.label||item.desktopID;name.append(link);const id=document.createElement('small');id.textContent=item.desktopID;name.append(id);state.textContent=tr(item.online?'online':'offline');button.textContent=tr('revoke');button.onclick=async()=>{if(!confirm(tr('confirm')))return;try{await api('/'+encodeURIComponent(item.desktopID),{method:'DELETE'});$('credential').hidden=true;$('credential').textContent='';$('message').textContent=tr('revoked');await load()}catch(e){showError(e)}};action.append(button);row.append(name,state,action);$('desktops').append(row)}$('manage').hidden=false}
$('login').onsubmit=async event=>{event.preventDefault();secret=$('secret').value;$('secret').value='';try{await load();$('message').textContent=''}catch(e){secret='';showError(e)}};$('refresh').onclick=()=>load().catch(showError);$('register').onsubmit=async event=>{event.preventDefault();try{const result=await api('',{method:'POST',body:JSON.stringify({desktopID:$('desktopID').value,label:$('label').value})});$('credential').hidden=false;$('credential').textContent=tr('once')+'\n'+tr('setup')+'\nRelay: '+location.origin+'\nDesktop ID: '+result.desktopID+'\nToken: '+result.token;$('register').reset();await load()}catch(e){showError(e)}};
</script></html>`
